name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4

      - name: Use Node.js v20
        uses: actions/setup-node@v5
        with:
          node-version: 22.20.0
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: build
        run: pnpm build

      - name: lint
        run: pnpm lint
